// WARNING: generated by `just generate` - manual changes will be overwritten
//! Bindings for `multicluster.x-k8s.io/v1beta1`, generated from
//! kubernetes-sigs/mcs-api v0.5.2 (32672de8605f9719b9220992c75cb263ba6f3746).

mod service_export;
mod service_import;

pub use service_export::*;
pub use service_import::*;
