// WARNING: generated by kopium - manual changes will be overwritten
// kopium command: kopium --filename manifests/crd/multicluster.x-k8s.io_serviceexports.yaml --api-version v1beta1 --docs --derive PartialEq --derive @enum:simple=Copy --derive @enum:simple=Eq --derive @enum:simple=Hash
// kopium version: 0.24.1

#[allow(unused_imports)]
mod prelude {
    pub use k8s_openapi::apimachinery::pkg::apis::meta::v1::Condition;
    pub use kube::CustomResource;
    pub use serde::{Deserialize, Serialize};
    pub use std::collections::BTreeMap;
}

use self::prelude::*;

/// spec defines the behavior of a ServiceExport.
#[derive(CustomResource, Serialize, Deserialize, Clone, Debug, PartialEq)]
#[kube(
    group = "multicluster.x-k8s.io",
    version = "v1beta1",
    kind = "ServiceExport",
    plural = "serviceexports"
)]
#[kube(namespaced)]
#[kube(status = "ServiceExportStatus")]
#[kube(schema = "disabled")]
#[kube(derive = "PartialEq")]
pub struct ServiceExportSpec {
    /// exportedAnnotations describes the annotations exported. It is optional for implementation.
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        rename = "exportedAnnotations"
    )]
    pub exported_annotations: Option<BTreeMap<String, String>>,
    /// exportedLabels describes the labels exported. It is optional for implementation.
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        rename = "exportedLabels"
    )]
    pub exported_labels: Option<BTreeMap<String, String>>,
}

/// status describes the current state of an exported service.
/// Service configuration comes from the Service that had the same
/// name and namespace as this ServiceExport.
/// Populated by the multi-cluster service implementation's controller.
#[derive(Serialize, Deserialize, Clone, Debug, PartialEq)]
pub struct ServiceExportStatus {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub conditions: Option<Vec<Condition>>,
}
